=== mitchellb1/trust-registration-api/public/api/conf/1.0/schemas/get-beneficiaries.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "id": "http://uk/gov/hmrc/trustregistration/raml/schemas/beneficiaries.json",
  "title": "Get Beneficiaries",
  "description": "A JSON response for all beneficiaries of any trust type with HATEOAS links for further actions",
  "type": "object",
  "properties": {
    "individualBeneficiaries": {
      "$ref": "#/definitions/individualBeneficiaries"
    },
    "employeeBeneficiaries": {
      "$ref": "#/definitions/individualBeneficiaries"
    },
    "directorBeneficiaries": {
      "$ref": "#/definitions/individualBeneficiaries"
    },
    "charityBeneficiaries": {
      "$ref": "#/definitions/charityBeneficiaries"
    },
    "otherBeneficiaries": {
      "$ref": "#/definitions/otherBeneficiaries"
    },
    "_links": {
      "type": "object",
      "properties": {
        "self": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          },
          "required": [
            "href"
          ]
        },
        "trust": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          },
          "required": [
            "href"
          ]
        }
      },
      "required": [
        "self",
        "trust"
      ]
    }
  },
  "required": ["_links"],
  "anyOf": [
    {
      "required": ["individualBeneficiaries"]
    },
    {
      "required": ["employeeBeneficiaries"]
    },
    {
      "required": ["directorBeneficiaries"]
    },
    {
      "required": ["charityBeneficiaries"]
    },
    {
      "required": ["otherBeneficiaries"]
    }
  ],
  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "isNonUkAddress": {
          "type": "boolean"
        },
        "line1": {
          "type": "string"
        },
        "line2": {
          "type": "string"
        },
        "line3": {
          "type": "string"
        },
        "line4": {
          "type": "string"
        },
        "postalCode": {
          "type": "string"
        },
        "country": {
          "type": "string"
        }
      },
      "required": [
        "line1",
        "isNonUkAddress"
      ]
    },
    "individual": {
      "description": "Individual details",
      "type": "object",
      "properties": {
        "givenName": {
          "type": "string"
        },
        "otherName": {
          "type": "string"
        },
        "familyName": {
          "type": "string"
        },
        "dateOfBirth": {
          "type": "string"
        },
        "nino": {
          "type": "string"
        },
        "dateOfDeath": {
          "type": "string"
        },
        "passport": {
          "type": "object",
          "properties": {
            "identifier": {
              "type": "string"
            },
            "expiryDate": {
              "type": "string"
            },
            "countryOfIssue": {
              "type": "string"
            }
          },
          "required": [
            "identifier",
            "expiryDate",
            "countryOfIssue"
          ]
        },
        "correspondenceAddress": {
          "$ref": "#/definitions/address"
        },
        "telephoneNumber": {
          "type": "string"
        }
      },
      "required": [
        "givenName",
        "familyName",
        "dateOfBirth"
      ]
    },
    "individualBeneficiaries": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "individual" : {"$ref": "#/definitions/individual"},
          "isVulnerable": {
            "type": "boolean"
          },
          "isIncomeAtTrusteeDiscretion": {
            "type": "boolean"
          },
          "shareOfIncome": {
            "type": "number"
          }
        },
        "required": [
          "individual",
          "isIncomeAtTrusteeDiscretion",
          "isVulnerable"
        ]
      }
    },
    "charityBeneficiaries": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "number": {
            "type": "string"
          },
          "correspondenceAddress": {
            "$ref": "#/definitions/address"
          },
          "isIncomeAtTrusteeDiscretion": {
            "type": "boolean"
          },
          "shareOfIncome": {
            "type": "number"
          }
        },
        "required": [
          "name",
          "number",
          "correspondenceAddress",
          "isIncomeAtTrusteeDiscretion"
        ]
      }
    },
    "otherBeneficiaries": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "correspondenceAddress": {
            "$ref": "#/definitions/address"
          },
          "isIncomeAtTrusteeDiscretion": {
            "type": "boolean"
          },
          "shareOfIncome": {
            "type": "number"
          }
        },
        "required": [
          "description",
          "correspondenceAddress",
          "isIncomeAtTrusteeDiscretion"
        ]
      }
    }
  }
}

=== mitchellb1/trust-registration-api/public/api/conf/1.0/examples/get-beneficiaries.json
{
  "individualBeneficiaries": [
    {
      "individual": {
        "title": "Mr",
        "givenName": "Joe",
        "otherName": "Fred",
        "familyName": "Bloggs",
        "dateOfBirth": "3000-01-01",
        "nino": "WA123456A",
        "passport": {
          "identifier": "123435egxb",
          "expiryDate": "3000-01-01",
          "countryOfIssue": "UK"
        },
        "correspondenceAddress": {
          "isNonUkAddress": false,
          "line1": "Line 1",
          "line2": "Line 2",
          "line3": "Line 3",
          "line4": "Line 4",
          "postalCode": "NE1 2BR",
          "country": "UK"
        }
      },
      "isVulnerable": false,
      "isIncomeAtTrusteeDiscretion": true,
      "shareOfIncome": 30
    }
  ],
  "charityBeneficiaries": [
    {
      "name": "Charity Name",
      "number": "123456789087654",
      "correspondenceAddress": {
        "isNonUkAddress": false,
        "line1": "Line 1",
        "line2": "Line 2",
        "line3": "Line 3",
        "line4": "Line 4",
        "postalCode": "NE1 2BR",
        "country": "UK"
      },
      "isIncomeAtTrusteeDiscretion": false,
      "shareOfIncome": 20
    }
  ],
  "otherBeneficiaries": [
    {
      "description": "Beneficiary Description",
      "correspondenceAddress": {
        "isNonUkAddress": false,
        "line1": "Line 1",
        "line2": "Line 2",
        "line3": "Line 3",
        "line4": "Line 4",
        "postalCode": "NE1 2BR",
        "country": "UK"
      },
      "isIncomeAtTrusteeDiscretion": false,
      "shareOfIncome": 50
    }
  ],
  "_links": {
    "self": {
      "href" : "/trusts/2234567890/beneficiaries"
    },
    "trust": {
      "href" : "/trusts/2234567890"
    }
  }
}
